/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainInterface;

import EquationEditor.Tree.MathObject;
import java.awt.Component;
import java.awt.Container;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import MainInterface.Tree;
import Nodes.EquationInfo;

/**
 *
 * @author Administrator
 */
public class AddEquationNodePopUpMenu extends javax.swing.JPopupMenu implements ActionListener {

    /**
     * Creates new form AddEquationNodePopUpMenu
     */
    private Tree.TreeStatic parent ;
    ActionListener menuListener;
    private final String ADD = "Add New Equation";
    private final String DELETE = "Delete this Equation";
    private final String EDIT = "Edit this Equation";
    private EquationInfo eqObj = null;
    public AddEquationNodePopUpMenu(Tree.TreeStatic tree, EquationInfo EqObj) {
        super();
        parent = tree;
        JMenuItem item1 = MakeMenuItem(ADD);
        add(item1);
        JMenuItem item2 = MakeMenuItem(DELETE);
        add(item2);
        JMenuItem item3 = MakeMenuItem(EDIT);
        add(item3);
        eqObj = EqObj;
    }
    
    private JMenuItem MakeMenuItem(String label){
        JMenuItem item = new JMenuItem(label);
        item.setActionCommand(label);
        item.addActionListener(this);
        return item;
    }
    public void actionPerformed(ActionEvent e) {
    String choice = e.getActionCommand();
    if (choice.equals(ADD))
        parent.AddNewEquation();
    else if (choice.equals(DELETE))
      parent.DeleteExistingEquation(eqObj);
    else if (choice.equals(EDIT))
        parent.EditExistingEquation(eqObj);
  }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
class MousePopupListener extends MouseAdapter {
  
    public void mouseClicked(MouseEvent e) {
        JOptionPane.showMessageDialog(null, "PHELLO");
    }
     public void mousePressed(MouseEvent e) {
      JOptionPane.showMessageDialog(null, "PHeeELLO");
    }

  }
}
