/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainInterface;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
/**
 *
 * @author Administrator
 */
public class SplitPanel extends javax.swing.JPanel {
    private Tree.TreeStatic treePane;
    private JPanel rightPane;
    private JSplitPane splitter;
    
    

    /**
     * Creates new form SplitPanel
     */
    public SplitPanel() {
        //OuterClass.StaticNestedClass nestedObject =
    // new OuterClass.StaticNestedClass();
        //Tree outerTree = new Tree();
        //Tree tree = new Tree();
        treePane = new Tree.TreeStatic();
        splitter = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
        rightPane = new JPanel();
        JScrollPane rightView = new JScrollPane(rightPane);
        JScrollPane leftView = new JScrollPane(treePane);
        
        Dimension minimumSize = new Dimension(600, 560);
        rightPane.setMinimumSize(minimumSize);
        treePane.setMinimumSize(minimumSize);
        splitter.setPreferredSize(new Dimension(800, 560));
        splitter.setLeftComponent(leftView);
        splitter.setRightComponent(rightView);
        splitter.setDividerLocation(200); 
        add(splitter);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


public void ChangeView(JPanel newPanel)
{
    rightPane.removeAll();
    rightPane.add(newPanel);
    revalidate();
    repaint();
   }
//public Tree.TreeStatic GetTree(){
//    return treePane;
//}
}
